### ISSUE TITLE
Missing Input Map Options

### ISSUE THREAD

**Issue by newoski** [libretro/beetle-wswan-libretro#4]
When comparing input mapping to Mednafen, I see 2 inputs missing:

;wswan, Built-In, Gamepad: Rapid A
;wswan, Built-In, Gamepad: Rapid B

They aren't listed in the Mednafen WSWAN documentation, but they are exposed during mapping and are visible in the Mednafen.cfg file. 

Is there a reason they are not exposed for mapping in RetroArch or is this a bug?

(This makes it impossible to play horizontally oriented games)

**Comment by newoski** [comment]
Anybody?

**Comment by twinaphex** [comment]
Could be hooked up, are these actual physical buttons on the device itself?

**Comment by newoski** [comment]
Not exactly. From what I can, they make things easier/more logical for mapping. 

As an example, Rockman on WonderSwan uses the 2 extra buttons as Turbo buttons. Other games, like Silversword, are completely unplayable without them...

**Comment by newoski** [comment]
So essentially, without connecting them to input mailing functions, the core is unusable fully. I'd be thrilled to see them connnected

**Comment by newoski** [comment]
Is this an easy fix? Any idea how long it will take? I love this system and can't wait to have it fully working in RetroArch

**Comment by vaguerant** [comment]
These seem like emulator turbo buttons, they have nothing to do with the WonderSwan hardware. Use RetroArch's turbo button implementation instead.

**Comment by newoski** [comment]
Sorta, kinda, not really. They function as turbo buttons for horizontal games, but they are part of the regular controls for vertical games. As a trial, test Judgement Silversword on WonderSwan Color. It is completely unplayable without using these buttons. Test and report back. If there's a workaround that doesn't require code change, I'd be giddy!

**Comment by vaguerant** [comment]
I think you must be confused in some way. Here's the layout of the buttons on the WonderSwan line when viewed horizontally:
```
|    Y1                            |
|  Y4  Y2                          |
|    Y3                            |
|              (screen)            |
|    X1                            |
|  X4  X2                       A  |
|    X3                       B    |
```
In horizontal games, you play using the X buttons (like a D-Pad) and the A/B buttons. The Y buttons are occasionally still used in this mode, but mostly not.

And when viewed vertically:

```
|                 A    |
|                   B  |
|                      |
|                      |
|       (screen)       |
|                      |
|                      |
|    Y2          X2    |
|  Y1  Y3      X1  X3  |
|    Y4          X4    |
```

In vertical games, the console is rotated 90 degrees to the left, and you play using the Y buttons (like a D-Pad) and the X buttons. I'm not aware of any games where A/B are still used in this mode, but they probably exist.

All of these buttons (Y1-4, X1-4, A and B) are mappable in RetroArch currently. You will need to substantially remap the buttons on any standard controller since they don't share the odd layout of the WonderSwan, but I was just playing Judgement Silversword a few minutes ago in RetroArch, there's no need at all for "turbo buttons".

**Comment by newoski** [comment]
Thanks so much for the quick reply. I'll test again tonight... any chance you could post a pastebin with your current WonderSwan core config? I'll test using that tonight on my system and report back.

**Comment by vaguerant** [comment]
I actually use the "Core Input Remapping" function in the Quick Menu and set a Game Remap for any vertical titles I wish to play. Here's my remap:

```
input_player1_b = "10"
input_player1_y = "1"
input_player1_select = "2"
input_player1_start = "3"
input_player1_up = "9"
input_player1_down = "0"
input_player1_left = "1"
input_player1_right = "8"
input_player1_a = "11"
input_player1_x = "9"
input_player1_l = "6"
input_player1_r = "7"
input_player1_l2 = "5"
input_player1_r2 = "4"
input_player1_l3 = "14"
input_player1_r3 = "15"
input_player1_l_x = "0"
input_player1_l_y = "1"
input_player1_r_x = "2"
input_player1_r_y = "3"
```
If you use Settings > Configuration > Load Remap Files Automatically you can save Game Remaps in the Core Input Remapping menu for any vertically-oriented games to have RetroArch switch to your vertical layout automatically whenever you start one of them up. My remap, however, is set up for use *without* rotating the display in RetroArch (i.e. it is intended for rotating the real-world, physical display instead), so the buttons will all be 90 degrees off correct for a user rotating using RetroArch. It should get you on the right track, though. This layout puts the Y buttons on the left D-Pad and the X buttons on the right face buttons in RetroArch. The "A/B" buttons are placed on the L/R shoulder buttons.

**Comment by newoski** [comment]
With the 90 degree logic in mind, could you post your regular, non-vertical, mapping for this system then?

**Comment by vaguerant** [comment]
Hahaha, I was specifically trying to avoid doing that because it's so damn confusing. ;) No problem, though, I'll give it a shot. What I believe should be correct (can't test it currently) for playing vertical games rotated *by RetroArch* is the following remap:
```
input_player1_b = "10"
input_player1_y = "1"
input_player1_select = "2"
input_player1_start = "3"
input_player1_up = "1"
input_player1_down = "8"
input_player1_left = "0"
input_player1_right = "9"
input_player1_a = "11"
input_player1_x = "9"
input_player1_l = "5"
input_player1_r = "4"
input_player1_l2 = "7"
input_player1_r2 = "6"
input_player1_l3 = "14"
input_player1_r3 = "15"
input_player1_l_x = "0"
input_player1_l_y = "1"
input_player1_r_x = "2"
input_player1_r_y = "3"
```
This puts the Y buttons on the D-Pad (but rotated 90 degrees left), the X buttons on the face buttons (but rotated 90 degrees left) and B/A are still on L/R (not changed at all).

**Comment by retro-wertz** [comment]
back to main topic:

this should be an invalid report, since its talking about mednafen's turbo A/B buttons. original Wonderswan hardware just have normal A and B buttons, the X/Y cursors are not even remapped to be turbo buttons in rotated games.
